name: 'Build LaTex Document'
# Controls when the workflow will run
on:
  workflow_call: # This allows it to be called from another workflow
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tectonic Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      # Setting up Tectonic
      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          tectonic-version: 0.15
          biber-version: 2.17
      - name: Run Tectonic
        run: |
          MKFILES=$(find src -type f -name '.*.mk' -o -name '*.mk' -printf '%P ')
          for mkfile in $MKFILES; do
            echo "Including makefile: $mkfile"
            source "$mkfile"
          done
          if [ -z "$TEXFILES" ]; then
            echo "TEXFILES not set, finding all .tex files in src/"
            TEXFILES=$(find src -type f -name '*.tex' -printf '%P ')
          fi

          mkdir -p out
          echo "Compiling: $TEXFILES"
          for file in $TEXFILES; do
            tectonic -C compile "src/$file" --outdir=out
          done
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: ./out/*.pdf