# This is a basic workflow to help you get started with Actions

name: 'LaTeX build'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setting up LaTeX
      - name: Install TeX Live and Biber
        run: sudo apt-get update && sudo apt-get install -y biber

      # Setting up Tectonic
      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile file
        run: tectonic ./paper/ccb.tex

      # Compiling the PDF
      - name: Upload compiled pdf
        uses: actions/upload-artifact@v4
        with:
          name: main-paper
          path: ./paper/ccb.pdf

      # Publishing the PDF as Release
      - name: Upload as release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: ./paper/ccb.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
